### ISSUE TITLE
Set max = 20 system

### ISSUE THREAD

**Issue by cheungszeleung** [stuartlynn/nameexoworlds.org#17]
Limit each organisation's selection up to 20.

https://exoplanetnamer.herokuapp.com/clubs/1
We are asking you to select systems to be taken to the next stage of the naming proces. You can select as many systems as you like but only once on each system

change to 
You can select "up to 20" systems as you like but only once on each system.

**Comment by stuartlynn** [comment]
This should now be in place and the prompt should be active
