### ISSUE TITLE
Problem with 16 character max

### ISSUE THREAD

**Issue by cheungszeleung** [stuartlynn/nameexoworlds.org#23]
The planet names are now currently set for 16 character max, but actually space is allowed. 

2nd, I found that the illegal char like $#@ can bypass the system;

3rd, I cannot delete any char after I enter 16 chars

**Comment by stuartlynn** [comment]
1st this should be better now

2nd Just want to clarify what is allowed here 0-9 a-z A-Z '  ? What characters should be allowed

3rd this should be resolved now. It was a firefox issue.

**Comment by stuartlynn** [comment]
@cheungszeleung

**Comment by cheungszeleung** [comment]
0-9 a-z A-Z and space

**Comment by cheungszeleung** [comment]
thanks, 1st and 3rd are resolved

**Comment by stuartlynn** [comment]
Should be resolved
