### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by cheungszeleung** [stuartlynn/nameexoworlds.org#26]
Could you also show the list of the 20 exoworlds 
with these sessions as well?

1 exoplanet (5 systems)									
1 star + 1 exoplanet (10 systems)									
1 star + 2 exoplanets (1 system)									
 1 star + 3 exoplanets (2 systems)
1 star + 1 exoplanets (1 system)		
1 star + 1 exoplanets (1 system)		

Full list
https://docs.google.com/spreadsheets/d/140UJw5zbDSzaYBWKSxatZNXE0dblhovbcwttI2YdgSs/edit#gid=0

**Comment by stuartlynn** [comment]
Hey I have tweaked this a little so that the 20 systems are show 1 per line with a planet count. Think this is the same thing
