### ISSUE TITLE
About the updated layout

### ISSUE THREAD

**Issue by cheungszeleung** [stuartlynn/nameexoworlds.org#34]
I think the new table for the 20 systems is clear

but the new problem arouse when we want to select them they have to go to the full list to locate them which is quite not user-friendly, in addition, it seems all the systems display "save the submission" button, which is very confusing

**Comment by cheungszeleung** [comment]
@stuartlynn

**Comment by stuartlynn** [comment]
That was  a bug. Have tweeked things to make it clearer all round whats happening
